version: '3.5'

services:
  database:
    image:  mysql:5.7
    container_name: db
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db:/var/lib/mysql
    networks:
      - usereats

networks:
  usereats:
    driver: bridge
    name: usereats

volumes:
  db:
